//src/app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";

//import { QueryClientProvider } from "@tanstack/react-query";
//import { queryClient } from "@/lib/queryClient";

import ReactQueryProvider from "@/lib/ReactQueryProvider";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body> 
        <ReactQueryProvider>
          {children}
        </ReactQueryProvider>
      </body>
    </html>
  );
}
